version: 2

project_name: bullstream

before:
  hooks:
    - go mod tidy

builds:
  - id: client
    main: ./cmd/client
    binary: bullstream-client
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: server
    main: ./cmd/server
    binary: bullstream-server
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

upx:
  - enabled: true
    ids: [client, server]
    compress: best
    lzma: true
    brute: false

archives:
  - id: client
    ids: [client]
    name_template: "bullstream-client_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    files:
      - DESIGN.md

  - id: server
    ids: [server]
    name_template: "bullstream-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    files:
      - DESIGN.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
